language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  app: skeleton-java-app
  api_key:
    secure: ARsRCU+mYxqod3Ita/hydlR5KR7OYJF0myCI9+L1kgJZj3GFk08igkKhBgv1P0nCsT/qSJi2ztJvpbnhEa1XL2KjYYmb47WYiReyNiNiAm2IhfiZQUNUK1GO+xKXoMaY8ucZwr9SCBiczXyyg0aQdeH2lVlo/3MKEfWfhNwyqAKCVIrJ0Zqxz9J2wT6oLgNJ4zHVgx9UR2ulRH4drg6BcjCNFN65RoF5HlerMSA0tAsOPzwgg0OgT98LeZR0mwyXVBeBzegjks8bF5kJh/FYV6j7IvJfF9udW9VZjpNbYqS4T6Pu/yNS6EkRhAgN8AJV6Y7wNKqPflTerLnpnp9x7H/L4LmFyq3A2YOzrYzMoupV8WeDw5Bl1LkIgAK81V7BWPvFJfExy2qTGEegyUXHe2wcsVSvarlnVSBZeQmYvf486cqzYWEw5gZ7JrIAk5eTAbbpoChgOICv+xhH5BkdfbU83aNejJp5ja7XrgG2poWZVvU5cVHlwZN6nhHfFCP6QKhv3bEa++tvrnNPIEoQR+oE414BrRR1h2UfObJ1l9TzMxCb+cupYz63ciBpKD5hRfcheaLDkoovKpWMfsj+GUxjAywMB6421YbFnVEXLTU39I0n6eZ4ESILoHjGnmhqVKgpp4A0OUZTT7U1bCLy1FnbNwSyqZVv1z+7q6Ja4UU=
